### PR TITLE
Week 5 progress

### PR DESCRIPTION
**Pull request by Maxwell-Lindsey**
Added primitive frontend, changed from Neural Net to Convulotional Neural Net

### CODE REVIEW

**Comment by DSohn5497** [comment]
Looks good!

**Review by DSohn5497 — APPROVED** [review]
Nothing to change!

**Comment by jacobc2700** [comment]
Yep, looks good.

**Comment by DanBurMur** [comment]
Looks good!

**Comment by Maxwell-Lindsey** [comment]
Looks good

**Pull request merged**
